### PR TITLE
[CCXDEV-14599] Update ccx-messaging to 4.1.5 to fix security issues

### PR DESCRIPTION
**Pull request by matysek**
# Description

[CCXDEV-14599] Update ccx-messaging to 4.1.5 to fix security issues

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by juandspy — APPROVED** [review]

**Review by juandspy — CHANGES_REQUESTED** [review]
CI is failing

**Comment by matysek** [comment]
replaced by this PR: https://github.com/RedHatInsights/dvo-extractor/pull/135

**Pull request closed without merging**
